
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."banners" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "img_url" "text" NOT NULL,
    "filetype" "text" NOT NULL
);

ALTER TABLE "public"."banners" OWNER TO "postgres";

COMMENT ON TABLE "public"."banners" IS 'Table for referencing banner data';

COMMENT ON COLUMN "public"."banners"."name" IS 'Banner name';
COMMENT ON COLUMN "public"."banners"."img_url" IS 'Storage link to banner image';
COMMENT ON COLUMN "public"."banners"."filetype" IS 'Banner filetype - should be image/*';

ALTER TABLE "public"."banners" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."banners_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."cart_items" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "cart_id" bigint,
    "product_id" bigint NOT NULL,
    "recipient_id" bigint,
    "selected_tier" bigint,
    "card_message" "text" DEFAULT '""'::"text" NOT NULL,
    "delivery_instructions" "text" DEFAULT '""'::"text" NOT NULL,
    "delivery_date" "date" NOT NULL
);

ALTER TABLE "public"."cart_items" OWNER TO "postgres";

COMMENT ON TABLE "public"."cart_items" IS 'This is a duplicate of order_items';

COMMENT ON COLUMN "public"."cart_items"."cart_id" IS 'Which cart this cart item belongs to';

ALTER TABLE "public"."cart_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cart_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."carts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sender_id" bigint
);

ALTER TABLE "public"."carts" OWNER TO "postgres";

COMMENT ON TABLE "public"."carts" IS 'Pre-checkout carts for authenticated users';

ALTER TABLE "public"."carts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."carts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."order_items" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "order_id" bigint,
    "product_id" bigint,
    "recipient_id" bigint,
    "selected_tier" bigint,
    "card_message" "text",
    "delivery_instructions" "text",
    "recip_first" "text",
    "recip_last" "text"
);

ALTER TABLE "public"."order_items" OWNER TO "postgres";

COMMENT ON TABLE "public"."order_items" IS 'Items that have been sent to recipients';

COMMENT ON COLUMN "public"."order_items"."recip_first" IS 'recipient''s first name';

COMMENT ON COLUMN "public"."order_items"."recip_last" IS 'recipient''s last name';

ALTER TABLE "public"."order_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."order_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."orders" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sender_id" bigint,
    "stripe_pi_id" "text",
    "sender_first" "text",
    "sender_last" "text",
    "sender_phone" "text" NOT NULL,
    "sender_email" "text",
    "order_prices" "jsonb" NOT NULL,
    "payment_status" "text",
    "recip_street_1" "text",
    "recip_street_2" "text",
    "recip_town_city" "text",
    "recip_state" "text",
    "recip_zip" "text",
    "delivery_date" "text"
);

ALTER TABLE "public"."orders" OWNER TO "postgres";

COMMENT ON TABLE "public"."orders" IS 'list of orders by customers';

COMMENT ON COLUMN "public"."orders"."sender_id" IS 'id of sender; either int ID or null, if user is anonymous';

COMMENT ON COLUMN "public"."orders"."stripe_pi_id" IS 'Stripe payment intent ID for reference';

COMMENT ON COLUMN "public"."orders"."sender_first" IS 'Sender''s first name';

COMMENT ON COLUMN "public"."orders"."sender_last" IS 'Sender''s last name';

COMMENT ON COLUMN "public"."orders"."sender_phone" IS 'sender''s phone number';

COMMENT ON COLUMN "public"."orders"."sender_email" IS 'Sender''s email address';

COMMENT ON COLUMN "public"."orders"."order_prices" IS 'POJO containing order pricing summary.';

COMMENT ON COLUMN "public"."orders"."payment_status" IS 'Status of payment as informed by stripe''s payment_intent';

COMMENT ON COLUMN "public"."orders"."recip_street_1" IS 'Street address 1 for recipient';

COMMENT ON COLUMN "public"."orders"."recip_street_2" IS 'street address 2 for recipient';

COMMENT ON COLUMN "public"."orders"."recip_town_city" IS 'recipient''s town/city';

COMMENT ON COLUMN "public"."orders"."recip_state" IS 'recipient''s state';

COMMENT ON COLUMN "public"."orders"."recip_zip" IS 'recipient''s zip code';

COMMENT ON COLUMN "public"."orders"."delivery_date" IS 'delivery date for this order';

ALTER TABLE "public"."orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."product_categories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "modified_at" timestamp with time zone
);

ALTER TABLE "public"."product_categories" OWNER TO "postgres";

COMMENT ON TABLE "public"."product_categories" IS 'List of categories for products';

COMMENT ON COLUMN "public"."product_categories"."is_active" IS 'Active status of category';

ALTER TABLE "public"."product_categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."product_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."products" (
    "created_at" timestamp with time zone,
    "name" "text",
    "description" "text",
    "standard_price" double precision,
    "premium_price" double precision,
    "deluxe_price" double precision,
    "image_url" "text",
    "categories" bigint[],
    "modified_at" timestamp with time zone,
    "id" bigint NOT NULL,
    "prices" bigint[] NOT NULL,
    "alt_image_urls" "text"[]
);

ALTER TABLE "public"."products" OWNER TO "postgres";

COMMENT ON TABLE "public"."products" IS 'product descriptions';

COMMENT ON COLUMN "public"."products"."prices" IS '[standard_price, premium_price, deluxe_price] - expressed in dollar cents.';

COMMENT ON COLUMN "public"."products"."alt_image_urls" IS 'other urls for alt views or versions of product.';

ALTER TABLE "public"."products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "is_admin" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "modified_at" timestamp with time zone,
    "id" bigint NOT NULL
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

COMMENT ON TABLE "public"."profiles" IS 'user profiles';

COMMENT ON COLUMN "public"."profiles"."id" IS 'serial ID';

ALTER TABLE "public"."profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."profiles__id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."recipients" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "street_address_1" "text",
    "street_address_2" "text",
    "town_city" "text",
    "zip" "text",
    "phone" "text" NOT NULL,
    "id" bigint NOT NULL,
    "sender_id" bigint,
    "state" "text"
);

ALTER TABLE "public"."recipients" OWNER TO "postgres";

COMMENT ON TABLE "public"."recipients" IS 'order recipients';

COMMENT ON COLUMN "public"."recipients"."state" IS 'Recipient''s state of residence';

ALTER TABLE "public"."recipients" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."recipients_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."cart_items"
    ADD CONSTRAINT "cart_items_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."carts"
    ADD CONSTRAINT "carts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."product_categories"
    ADD CONSTRAINT "product_categories_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."product_categories"
    ADD CONSTRAINT "product_categories_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."product_categories"
    ADD CONSTRAINT "product_categories_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "product_details_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "product_details_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."recipients"
    ADD CONSTRAINT "recipients_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."cart_items"
    ADD CONSTRAINT "cart_items_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "public"."carts"("id");

ALTER TABLE ONLY "public"."cart_items"
    ADD CONSTRAINT "cart_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id");

ALTER TABLE ONLY "public"."cart_items"
    ADD CONSTRAINT "cart_items_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "public"."recipients"("id");

ALTER TABLE ONLY "public"."carts"
    ADD CONSTRAINT "carts_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id");

ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id");

ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "public"."recipients"("id");

ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."profiles"("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "public_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."recipients"
    ADD CONSTRAINT "recipients_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."profiles"("id");

CREATE POLICY "Public read access" ON "public"."banners" FOR SELECT USING (true);

CREATE POLICY "Admin write access" ON "public"."banners" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."user_id" = "auth"."uid"()) AND ("p"."is_admin" = true)))));

CREATE POLICY "Admin write access" ON "public"."products" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."user_id" = "auth"."uid"()) AND ("p"."is_admin" = true)))));

CREATE POLICY "Authenticated uers can freely interact with their carts" ON "public"."carts" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE ("p"."user_id" = "auth"."uid"()))));

CREATE POLICY "Authenticated users can freely interact with their cart items." ON "public"."cart_items" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE ("p"."user_id" = "auth"."uid"()))));

CREATE POLICY "Delete for own profile and admins" ON "public"."profiles" FOR DELETE USING (true);

CREATE POLICY "Public Account Creation" ON "public"."profiles" FOR INSERT WITH CHECK ((NOT (EXISTS ( SELECT 1
   FROM "public"."profiles" "profiles_1"
  WHERE ("profiles_1"."user_id" = "auth"."uid"())))));

CREATE POLICY "Public User Policy" ON "public"."product_categories" FOR SELECT USING (true);

CREATE POLICY "Users can select and change their own recipients" ON "public"."recipients" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE ("p"."user_id" = "auth"."uid"()))));

CREATE POLICY "Users can view their orders items." ON "public"."order_items" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE ("p"."user_id" = "auth"."uid"()))));

CREATE POLICY "admin_policy" ON "public"."product_categories" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."user_id" = "auth"."uid"()) AND ("p"."is_admin" = true)))));

CREATE POLICY "authenticated users can place orders" ON "public"."orders" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE ("p"."user_id" = "auth"."uid"()))));

ALTER TABLE "public"."banners" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."cart_items" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."carts" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."order_items" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."product_categories" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public access to product information" ON "public"."products" FOR SELECT USING (true);

CREATE POLICY "read_access" ON "public"."profiles" FOR SELECT TO "authenticated" USING (("user_id" = "auth"."uid"()));

ALTER TABLE "public"."recipients" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "update own profile" ON "public"."profiles" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."user_id" = "auth"."uid"()) OR (("p"."user_id" = "auth"."uid"()) AND "p"."is_admin")))));

CREATE POLICY "users can place an order" ON "public"."order_items" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE ("p"."user_id" = "auth"."uid"()))));

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."banners" TO "anon";
GRANT ALL ON TABLE "public"."banners" TO "authenticated";
GRANT ALL ON TABLE "public"."banners" TO "service_role";

GRANT ALL ON SEQUENCE "public"."banners_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."banners_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."banners_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."cart_items" TO "anon";
GRANT ALL ON TABLE "public"."cart_items" TO "authenticated";
GRANT ALL ON TABLE "public"."cart_items" TO "service_role";

GRANT ALL ON SEQUENCE "public"."cart_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cart_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cart_items_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."carts" TO "anon";
GRANT ALL ON TABLE "public"."carts" TO "authenticated";
GRANT ALL ON TABLE "public"."carts" TO "service_role";

GRANT ALL ON SEQUENCE "public"."carts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."carts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."carts_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."order_items" TO "anon";
GRANT ALL ON TABLE "public"."order_items" TO "authenticated";
GRANT ALL ON TABLE "public"."order_items" TO "service_role";

GRANT ALL ON SEQUENCE "public"."order_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."order_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."order_items_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."orders" TO "anon";
GRANT ALL ON TABLE "public"."orders" TO "authenticated";
GRANT ALL ON TABLE "public"."orders" TO "service_role";

GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."product_categories" TO "anon";
GRANT ALL ON TABLE "public"."product_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."product_categories" TO "service_role";

GRANT ALL ON SEQUENCE "public"."product_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."product_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."product_categories_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";

GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";

GRANT ALL ON SEQUENCE "public"."profiles__id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."profiles__id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."profiles__id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."recipients" TO "anon";
GRANT ALL ON TABLE "public"."recipients" TO "authenticated";
GRANT ALL ON TABLE "public"."recipients" TO "service_role";

GRANT ALL ON SEQUENCE "public"."recipients_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."recipients_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."recipients_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
